In [26]:
import pandas as pd

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
import matplotlib
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from matplotlib.pyplot import figure

In [27]:
#read in data and delete firs two rows and update header with 3rd row values
df = pd.read_excel("FrontiersDS.xlsx",sheet_name='Wide')
df = df.iloc[2:]
df = df.reset_index(drop=True)
new_header = df.iloc[0]
df = df[1:]
df.columns = new_header
df.head(50)

,Species,Strain,Samples,Ethyl Acetate,Ethanol,"Propanoic acid, ethyl ester",2-Pentanone,Decane,Methyl Isobutyl Ketone,Amylene hydrate,...,1-Dodecanol,Methyl tetradecanoate,2-Pentadecanone,"Tetradecanoic acid, ethyl ester",Hexadecanal,n-Tridecan-1-ol,1-Tetradecanol,n-Pentadecanol,1-Hexadecanol,Indole
1,SA,SA_A,SA.A_TSB_A,465374,1027715,NaN,1289650,800581,324424,73015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SA,SA_A,SA.A_TSB_B,193151,1050974,NaN,504113,294680,189630,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SA,SA_A,SA.A_TSB_C,403286,1850391,NaN,1169501,15,228163,73558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SA,SA_A,SA.A_TSB_D,129833,5140770,NaN,1926072,124282,0,188367,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,SA,SA_A,SA.A_TSB_E,117105,3422557,NaN,246751,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,SA,SA_B,SA.B_TSB_A,316764,914667,NaN,560337,456376,167165,90157,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SA,SA_B,SA.B_TSB_B,141636,801684,NaN,497068,408709,152829,139948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SA,SA_B,SA.B_TSB_C,292548,1037912,NaN,1102211,710674,228457,53152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SA,SA_B,SA.B_TSB_D,0,7091491,NaN,1336035,470055,0,210357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,SA,SA_B,SA.B_TSB_E,588447,8155560,NaN,1737916,201138,0,295857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SA,SA_A,SA.A_BHI_A,0,3054748,NaN,832334,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,SA,SA_A,SA.A_BHI_B,0,909704,NaN,444238,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SA,SA_A,SA.A_BHI_C,0,2419195,NaN,540199,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,SA,SA_A,SA.A_BHI_D,0,3195134,NaN,877468,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,SA,SA_A,SA.A_BHI_E,0,1208273,NaN,371852,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,SA,SA_B,SA.B_BHI_A,0,3077081,NaN,501780,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,SA,SA_B,SA.B_BHI_B,0,1659016,NaN,397547,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,SA,SA_B,SA.B_BHI_C,0,376521,NaN,73257,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,SA,SA_B,SA.B_BHI_D,0,1910296,NaN,523353,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,SA,SA_B,SA.B_BHI_E,0,1220898,NaN,500776,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,SA,SA_A,SA.A_LB_A,0,0,NaN,320965,0,68518,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,SA,SA_A,SA.A_LB_B,0,0,NaN,886309,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,SA,SA_A,SA.A_LB_C,0,0,NaN,515572,210972,657995,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,SA,SA_A,SA.A_LB_D,0,0,NaN,868238,209747,801038,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,SA,SA_A,SA.A_LB_E,0,0,NaN,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,SA,SA_B,SA.B_LB_A,0,0,NaN,840146,156567,1309090,103953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,SA,SA_B,SA.B_LB_B,0,0,NaN,1392228,245113,1062848,50444,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,SA,SA_B,SA.B_LB_C,0,0,NaN,785128,66082,1309090,105840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,SA,SA_B,SA.B_LB_D,0,0,NaN,1526229,548037,610468,71194,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,SA,SA_B,SA.B_LB_E,0,0,NaN,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,PA,PA_A,PA.A_BHI_A,72782,119451,NaN,217717,0,0,80981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,PA,PA_A,PA.A_BHI_B,158092,0,NaN,449020,0,0,295319,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,PA,PA_A,PA.A_BHI_C,154266,2755630,NaN,2741250,0,0,111457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,PA,PA_A,PA.A_BHI_D,165447,2864780,NaN,229514,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,PA,PA_A,PA.A_BHI_E,257291,2979582,NaN,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,PA,PA_B,PA.B_BHI_A,0,123501,NaN,405146,552437,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,PA,PA_B,PA.B_BHI_B,245490,5398605,NaN,738399,0,0,171282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,PA,PA_B,PA.B_BHI_C,464030,1418380,NaN,2816991,919172,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,PA,PA_B,PA.B_BHI_D,0,1132339,NaN,601736,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,PA,PA_B,PA.B_BHI_E,216975,1972423,NaN,601858,0,0,153432,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,PA,PA_A,PA.A_LB_A,0,0,NaN,4593791,2992449,0,759098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,PA,PA_A,PA.A_LB_B,0,2100747,NaN,1556357,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,PA,PA_A,PA.A_LB_C,0,0,NaN,818478,952843,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,PA,PA_A,PA.A_LB_D,0,0,NaN,925725,872643,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,PA,PA_A,PA.A_LB_E,0,0,NaN,635916,564067,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,PA,PA_B,PA.B_LB_A,0,0,NaN,1443975,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,PA,PA_B,PA.B_LB_B,0,0,NaN,430258,1105838,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,PA,PA_B,PA.B_LB_C,0,71200,NaN,612393,920844,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,PA,PA_B,PA.B_LB_D,0,0,NaN,521478,726757,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,PA,PA_B,PA.B_LB_E,0,0,NaN,1257192,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#Data Cleaning

#replace nulls with 0

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 1 to 84
Data columns (total 70 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Species                                        84 non-null     object
 1   Strain                                         84 non-null     object
 2   Samples                                        84 non-null     object
 3    Ethyl Acetate                                 83 non-null     object
 4   Ethanol                                        84 non-null     object
 5   Propanoic acid, ethyl ester                    27 non-null     object
 6   2-Pentanone                                    84 non-null     object
 7   Decane                                         84 non-null     object
 8   Methyl Isobutyl Ketone                         57 non-null     object
 9   Amylene hydrate                                84 non-null     object
 10  Butanoic acid, 2-methyl-, methyl ester         27 non-null     object
 11  Isobutyl acetate                               54 non-null     object
 12  Methyl isovalerate                             57 non-null     object
 13  1-Propanol                                     27 non-null     object
 14  Methyl thiolacetate                            83 non-null     object
 15  Butanoic acid, 2-methyl-, ethyl ester          30 non-null     object
 16  2-Hexanone                                     57 non-null     object
 17  Ethyl isocyanide                               27 non-null     object
 18  1-Propanol, 2-methyl-                          84 non-null     object
 19  2-Pentanol, 2-methyl-                          83 non-null     object
 20  2-Pentanol                                     57 non-null     object
 21  1-Butanol, 3-methyl-, acetate                  30 non-null     object
 22  1 - Undecene                                   27 non-null     object
 23  1-Butanol                                      54 non-null     object
 24  2-Heptanone                                    84 non-null     object
 25  Dodecane                                       54 non-null     object
 26  1-Butanol, 3-methyl-                           84 non-null     object
 27   S-Methyl 3-methylbutanethioate                27 non-null     object
 28  2-Heptanone, 4,6-dimethyl-                     54 non-null     object
 29   3-Buten-1-ol, 3-methyl-                       84 non-null     object
 30  Thiocyanic acid, methyl ester                  27 non-null     object
 31  Acetoin                                        84 non-null     object
 32  1-Pentanol, 2-methyl-                          27 non-null     object
 33  Butanoic acid, 3-methyl-, 2-methylbutyl ester  27 non-null     object
 34  2-Heptanol, 4-methyl-                          27 non-null     object
 35  2-Nonanone                                     54 non-null     object
 36  Acetic acid                                    57 non-null     object
 37  2-Nonanol                                      27 non-null     object
 38  Pyrrole                                        27 non-null     object
 39  1H-Pyrrole, 2-methyl-                          27 non-null     object
 40  1-Heptanol, 2,4-dimethyl-,                     54 non-null     object
 41  Propanoic acid                                 56 non-null     object
 42  Propanoic acid, 2-methyl-                      30 non-null     object
 43  1-Octanol                                      27 non-null     object
 44  2-Undecanone                                   54 non-null     object
 45  Benzoic acid, methyl ester                     54 non-null     object
 46  Butyrolactone                                  30 non-null     object
 47   Decanoic acid, ethyl ester                    27 non-null     object
 48  Acetic acid, decyl ester                       27 non-null     object
 49  2-Undecanol                                    54 non-null     object
 50  Butanoic acid, 3-methyl-                       30 non-null     object
 51  2-Dodecanone                                   27 non-null     object
 52  1-Decanol                                      27 non-null     object
 53  2-Tridecanone                                  27 non-null     object
 54   Dodecanoic acid, ethyl ester                  27 non-null     object
 55  1,4-Butanediol                                 30 non-null     object
 56  Phenylethyl Alcohol                            27 non-null     object
 57  Acetophenone, 2'-amino-                        27 non-null     object
 58  2-Tridecanol                                   27 non-null     object
 59  Tetradecanal                                   27 non-null     object
 60  1-Dodecanol                                    27 non-null     object
 61  Methyl tetradecanoate                          27 non-null     object
 62   2-Pentadecanone                               27 non-null     object
 63  Tetradecanoic acid, ethyl ester                27 non-null     object
 64  Hexadecanal                                    27 non-null     object
 65  n-Tridecan-1-ol                                27 non-null     object
 66  1-Tetradecanol                                 27 non-null     object
 67  n-Pentadecanol                                 26 non-null     object
 68   1-Hexadecanol                                 27 non-null     object
 69  Indole                                         27 non-null     object
dtypes: object(70)
memory usage: 46.1+ KB

In [29]:
 df = df.fillna(0)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 1 to 84
Data columns (total 70 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Species                                        84 non-null     object
 1   Strain                                         84 non-null     object
 2   Samples                                        84 non-null     object
 3    Ethyl Acetate                                 84 non-null     int64
 4   Ethanol                                        84 non-null     int64
 5   Propanoic acid, ethyl ester                    84 non-null     int64
 6   2-Pentanone                                    84 non-null     int64
 7   Decane                                         84 non-null     int64
 8   Methyl Isobutyl Ketone                         84 non-null     int64
 9   Amylene hydrate                                84 non-null     int64
 10  Butanoic acid, 2-methyl-, methyl ester         84 non-null     int64
 11  Isobutyl acetate                               84 non-null     int64
 12  Methyl isovalerate                             84 non-null     int64
 13  1-Propanol                                     84 non-null     int64
 14  Methyl thiolacetate                            84 non-null     int64
 15  Butanoic acid, 2-methyl-, ethyl ester          84 non-null     int64
 16  2-Hexanone                                     84 non-null     int64
 17  Ethyl isocyanide                               84 non-null     int64
 18  1-Propanol, 2-methyl-                          84 non-null     int64
 19  2-Pentanol, 2-methyl-                          84 non-null     int64
 20  2-Pentanol                                     84 non-null     int64
 21  1-Butanol, 3-methyl-, acetate                  84 non-null     int64
 22  1 - Undecene                                   84 non-null     int64
 23  1-Butanol                                      84 non-null     int64
 24  2-Heptanone                                    84 non-null     int64
 25  Dodecane                                       84 non-null     int64
 26  1-Butanol, 3-methyl-                           84 non-null     int64
 27   S-Methyl 3-methylbutanethioate                84 non-null     int64
 28  2-Heptanone, 4,6-dimethyl-                     84 non-null     int64
 29   3-Buten-1-ol, 3-methyl-                       84 non-null     int64
 30  Thiocyanic acid, methyl ester                  84 non-null     int64
 31  Acetoin                                        84 non-null     int64
 32  1-Pentanol, 2-methyl-                          84 non-null     int64
 33  Butanoic acid, 3-methyl-, 2-methylbutyl ester  84 non-null     int64
 34  2-Heptanol, 4-methyl-                          84 non-null     int64
 35  2-Nonanone                                     84 non-null     int64
 36  Acetic acid                                    84 non-null     int64
 37  2-Nonanol                                      84 non-null     int64
 38  Pyrrole                                        84 non-null     int64
 39  1H-Pyrrole, 2-methyl-                          84 non-null     int64
 40  1-Heptanol, 2,4-dimethyl-,                     84 non-null     int64
 41  Propanoic acid                                 84 non-null     int64
 42  Propanoic acid, 2-methyl-                      84 non-null     int64
 43  1-Octanol                                      84 non-null     int64
 44  2-Undecanone                                   84 non-null     int64
 45  Benzoic acid, methyl ester                     84 non-null     int64
 46  Butyrolactone                                  84 non-null     int64
 47   Decanoic acid, ethyl ester                    84 non-null     int64
 48  Acetic acid, decyl ester                       84 non-null     int64
 49  2-Undecanol                                    84 non-null     int64
 50  Butanoic acid, 3-methyl-                       84 non-null     int64
 51  2-Dodecanone                                   84 non-null     int64
 52  1-Decanol                                      84 non-null     int64
 53  2-Tridecanone                                  84 non-null     int64
 54   Dodecanoic acid, ethyl ester                  84 non-null     int64
 55  1,4-Butanediol                                 84 non-null     int64
 56  Phenylethyl Alcohol                            84 non-null     int64
 57  Acetophenone, 2'-amino-                        84 non-null     int64
 58  2-Tridecanol                                   84 non-null     int64
 59  Tetradecanal                                   84 non-null     int64
 60  1-Dodecanol                                    84 non-null     int64
 61  Methyl tetradecanoate                          84 non-null     int64
 62   2-Pentadecanone                               84 non-null     int64
 63  Tetradecanoic acid, ethyl ester                84 non-null     int64
 64  Hexadecanal                                    84 non-null     int64
 65  n-Tridecan-1-ol                                84 non-null     int64
 66  1-Tetradecanol                                 84 non-null     int64
 67  n-Pentadecanol                                 84 non-null     int64
 68   1-Hexadecanol                                 84 non-null     int64
 69  Indole                                         84 non-null     int64
dtypes: int64(67), object(3)
memory usage: 46.1+ KB

In [31]:
df.describe()

,Ethyl Acetate,Ethanol,"Propanoic acid, ethyl ester",2-Pentanone,Decane,Methyl Isobutyl Ketone,Amylene hydrate,"Butanoic acid, 2-methyl-, methyl ester",Isobutyl acetate,Methyl isovalerate,...,1-Dodecanol,Methyl tetradecanoate,2-Pentadecanone,"Tetradecanoic acid, ethyl ester",Hexadecanal,n-Tridecan-1-ol,1-Tetradecanol,n-Pentadecanol,1-Hexadecanol,Indole
count,8.400000e+01,8.400000e+01,84.000000,8.400000e+01,8.400000e+01,8.400000e+01,84.000000,8.400000e+01,84.000000,84.000000,...,8.400000e+01,84.000000,84.000000,84.000000,84.000000,84.000000,8.400000e+01,8.400000e+01,8.400000e+01,8.400000e+01
mean,2.036490e+05,2.028525e+06,5782.309524,1.064872e+06,2.768394e+05,1.480613e+05,86875.857143,9.232962e+04,29581.845238,66009.345238,...,6.746086e+05,31460.892857,27563.583333,3268.202381,30265.511905,27508.380952,1.883707e+05,5.355926e+04,2.128250e+05,2.650791e+07
std,3.002189e+05,2.590197e+06,27125.922554,1.005756e+06,4.261672e+05,3.360538e+05,150817.542074,2.878601e+05,72069.016020,149656.053293,...,1.526756e+06,110105.503047,66499.751208,17585.417257,100657.405300,83558.369196,4.141798e+05,2.594242e+05,6.134696e+05,4.067477e+07
min,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000,4.407430e+05,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,8.781000e+04,1.032814e+06,0.000000,6.556720e+05,3.304850e+04,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.661052e+05,3.060331e+06,0.000000,1.405165e+06,4.603455e+05,0.000000e+00,112542.750000,0.000000e+00,0.000000,0.000000,...,6.850748e+05,0.000000,0.000000,0.000000,0.000000,0.000000,1.589658e+05,0.000000e+00,1.292200e+04,7.229028e+07
max,1.335746e+06,1.073959e+07,175461.000000,4.593791e+06,2.992449e+06,1.309090e+06,759098.000000,1.437190e+06,381024.000000,634921.000000,...,8.172616e+06,698476.000000,382222.000000,119785.000000,652645.000000,448151.000000,2.450605e+06,1.869692e+06,4.268126e+06,1.127007e+08

In [34]:
df.head()

#samples = df["Samples "].unique()
#samples

df.to_csv('clean_data.csv')

In [ ]:
# create instance of labelencoder
labelencoder = LabelEncoder()
# Assign numerical values and store in a new column
clean_data['Species'] = labelencoder.fit_transform(clean_data['Study'])

# create instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

# passing on Study_no column values
enc_df = pd.DataFrame(enc.fit_transform(clean_data[['Study_no']]).toarray())

# rename columns as Study names
enc_df = enc_df.rename(columns={0: 'Fridberg', 1: 'Horstmann', 2: 'Kjome', 3: 'Maia', 6: 'SteingroverInPrep', 4: 'Premkumar', 8: 'Wood', 9: 'Worthy', 5: 'Steingroever2011', 7: 'Wetzels'})

# reset index before concatenation
clean_data.reset_index(inplace=True)
enc = pd.concat([clean_data, enc_df], axis=1)
enc

In [36]:
strain = df["Strain"].unique()
strain

array(['SA_A', 'SA_B', 'PA_A', 'PA_B', 'EC_A', 'EC_B'], dtype=object)

In [ ]:
sns.scatterplot(clusters_pca.iloc[:,0],clusters_pca.iloc[:,1], hue=processed_df.reset_index().PayScheme, palette='Set1', s=100, alpha=0.2).set_title('PCs Colour Coded by Payoff Scheme', fontsize=15)